/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#0050cb',
        'on-primary': '#ffffff',
        'primary-container': '#0066ff',
        'on-primary-container': '#f8f7ff',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-primary-fixed': '#001849',
        'on-primary-fixed-variant': '#003fa4',
        'inverse-primary': '#b3c5ff',
        'secondary': '#006c47',
        'on-secondary': '#ffffff',
        'secondary-container': '#8af5be',
        'on-secondary-container': '#00714b',
        'secondary-fixed': '#8df7c1',
        'secondary-fixed-dim': '#71dba6',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005235',
        'tertiary': '#7b5100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9c6700',
        'on-tertiary-container': '#fff7f1',
        'tertiary-fixed': '#ffddb3',
        'tertiary-fixed-dim': '#ffb950',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#624000',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f9f9ff',
        'on-surface': '#191c22',
        'on-surface-variant': '#424656',
        'surface-dim': '#d8d9e3',
        'surface-bright': '#f9f9ff',
        'surface-tint': '#0054d6',
        'surface-variant': '#e0e2ec',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3fd',
        'surface-container': '#ecedf7',
        'surface-container-high': '#e6e8f2',
        'surface-container-highest': '#e0e2ec',
        'outline': '#727687',
        'outline-variant': '#c2c6d8',
        'inverse-surface': '#2d3038',
        'inverse-on-surface': '#eff0fa',
        'background': '#f9f9ff',
        'on-background': '#191c22',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Outfit', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        data: ['"JetBrains Mono"', 'monospace'],
        display: ['Outfit', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        'display-lg': ['Outfit', 'sans-serif'],
        'display-lg-mobile': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'data-lg': ['"JetBrains Mono"', 'monospace'],
        'data-md': ['"JetBrains Mono"', 'monospace'],
        'data-sm': ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'glass': '0 12px 32px rgba(0, 80, 203, 0.08)',
        'card': '0 4px 20px rgba(0, 0, 0, 0.04)',
        'nav': '0 -4px 24px rgba(0, 0, 0, 0.06)',
        'gradient': '0 4px 16px rgba(0, 80, 203, 0.20)',
      },
    },
  },
  plugins: [],
}
